import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Rajluck Game Install – How to Install Rajluck APK on Android 2026",
  description: "Rajluck Game Install — step-by-step guide to install Rajluck Game APK on Android. Enable unknown sources, download, and install. rajluck game install, install rajluck, rajluck apk install.",
  keywords: ["Rajluck Game Install", "install Rajluck", "Rajluck APK install", "how to install Rajluck Game", "Rajluck Game setup", "Rajluck Game", "Rajluck", "Raj Luck Game Install", "RajluckGamers"],
  openGraph: { title: "Rajluck Game Install – APK Installation Guide 2026", description: "Install Rajluck Game APK on Android. Guide at rajluckgamers.com.", url: "https://rajluckgamers.com/rajluck-game-install", images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Rajluck Game Install" }] },
  twitter: { card: "summary_large_image", title: "Rajluck Game Install", images: ["/og-image.png"] },
  alternates: { canonical: "https://rajluckgamers.com/rajluck-game-install" },
};

const CTA_LINK = "https://share-rxapq9cajg.rajluck.co/web/share/index.html?ic=AA64CBGV&ts=1783054980&m=2&lang=en&id=1";

export default function Page() {
  return (
    <main className="min-h-screen bg-surface text-text-primary">
      {/* Hero */}
      <section className="hero-gradient section-padding text-center">
        <Image src="/logo.webp" alt="Rajluck Game Installation Guide" width={160} height={160} className="w-[100px] sm:w-[180px] mx-auto mb-6 drop-shadow-2xl animate-fade-in" priority />
        <h1 className="text-4xl sm:text-5xl font-extrabold text-black mb-4 animate-slide-up">Rajluck Game Installation</h1>
        <p className="text-xl text-black/80 mb-3 font-medium">Permissions &amp; Settings Guide for Android</p>
        <p className="text-base text-black/70 max-w-2xl mx-auto mb-8">
          Installing Rajluck Game on Android involves granting several system permissions. This guide explains exactly which permissions the app requests, why each one is necessary, what it means for your privacy, and how to manage them after installation.
        </p>
        <a href={CTA_LINK} target="_blank" rel="noopener noreferrer" className="btn-cta inline-block text-lg font-bold px-10 py-4 rounded-full shadow-xl animate-fade-in">
          Download &amp; Install Rajluck
        </a>
      </section>

      {/* Permissions Overview */}
      <section className="section-padding max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold gradient-text mb-6">App Permissions Explained</h2>
        <p className="text-text-secondary mb-8">
          When you install the Rajluck APK, Android will prompt you to grant specific permissions either at install time or the first time a feature needs them. Here is a full breakdown of every permission Rajluck requests and the precise reason for it.
        </p>
        <div className="space-y-4">
          {[
            {
              perm: "Internet Access",
              icon: "🌐",
              why: "Required for all gameplay, authentication, balance updates, and communication with Rajluck servers. Without this permission the app cannot function at all.",
              privacy: "No personal browsing data is accessed. The app only communicates with Rajluck's own servers.",
            },
            {
              perm: "Read / Write External Storage",
              icon: "💾",
              why: "Used to save downloaded APK update files, cached game assets, and user-generated screenshots of winnings. Storage access improves loading speed on repeated sessions.",
              privacy: "Rajluck does not read or transmit files outside its own app directory. The permission scope is sandboxed.",
            },
            {
              perm: "Push Notifications",
              icon: "🔔",
              why: "Enables real-time alerts for bonus credits, daily reminders, withdrawal confirmations, and security alerts such as new login detection.",
              privacy: "Notification content is generated by Rajluck servers and delivered through Android's notification system. No third-party trackers are involved.",
            },
            {
              perm: "Vibration",
              icon: "📳",
              why: "Provides haptic feedback during game events such as wins, bonus triggers, and UI interactions. Purely an experience enhancement.",
              privacy: "No data is collected or transmitted. This permission is entirely local and hardware-level.",
            },
            {
              perm: "Wake Lock",
              icon: "⚡",
              why: "Prevents the device screen from sleeping during active gameplay sessions, ensuring you do not lose your place in a game due to screen timeout.",
              privacy: "This permission does not grant access to any data. It only interacts with the power management system.",
            },
            {
              perm: "Network State",
              icon: "📶",
              why: "Allows the app to detect connection status changes — switching between WiFi and mobile data — so it can reconnect seamlessly and warn you before connectivity issues affect a session.",
              privacy: "Only connection type and state are read. No network traffic from other apps is accessible.",
            },
          ].map((item) => (
            <div key={item.perm} className="card p-6">
              <div className="flex items-center gap-3 mb-2">
                <span className="text-2xl">{item.icon}</span>
                <h3 className="font-bold text-text-primary text-lg">{item.perm}</h3>
              </div>
              <p className="text-text-secondary text-sm mb-2"><strong className="text-primary">Why needed:</strong> {item.why}</p>
              <p className="text-text-muted text-sm"><strong>Privacy note:</strong> {item.privacy}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Privacy Implications */}
      <section className="section-padding bg-primary-50 max-w-full">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold gradient-text mb-6">Privacy Implications of Each Permission</h2>
          <p className="text-text-secondary mb-8">
            Understanding the data scope of each permission helps you make an informed decision. The table below summarizes data access levels side by side.
          </p>
          <div className="overflow-x-auto">
            <table className="info-table w-full text-left">
              <thead>
                <tr>
                  <th className="p-3 bg-primary-100 font-semibold">Permission</th>
                  <th className="p-3 bg-primary-100 font-semibold">Data Accessed</th>
                  <th className="p-3 bg-primary-100 font-semibold">Transmitted Off-Device?</th>
                  <th className="p-3 bg-primary-100 font-semibold">Can Be Revoked?</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ["Internet Access", "None (connection pathway only)", "No personal data", "No — app stops working"],
                  ["Storage", "App-specific files only", "No", "Yes — disables caching"],
                  ["Notifications", "Notification content only", "No", "Yes — from Android settings"],
                  ["Vibration", "None", "No", "Yes — in app settings"],
                  ["Wake Lock", "None", "No", "Not applicable"],
                  ["Network State", "Connection type & status", "No", "Yes"],
                ].map(([perm, data, transmitted, revoke]) => (
                  <tr key={perm} className="border-b">
                    <td className="p-3 text-primary font-medium text-sm">{perm}</td>
                    <td className="p-3 text-text-secondary text-sm">{data}</td>
                    <td className="p-3 text-text-secondary text-sm">{transmitted}</td>
                    <td className="p-3 text-text-muted text-sm">{revoke}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Managing Permissions Post-Install */}
      <section className="section-padding max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold gradient-text mb-6">Managing Permissions After Installation</h2>
        <p className="text-text-secondary mb-8">
          You are not locked into any permission grant permanently. Android allows you to review and revoke permissions at any time without uninstalling the app.
        </p>
        <ol className="space-y-5">
          {[
            { step: "1", title: "Open Android Settings", desc: "Swipe down on your home screen and tap the gear icon, or find the Settings app in your app drawer." },
            { step: "2", title: "Navigate to Apps", desc: "Tap 'Apps' or 'Application Manager' depending on your Android version and device manufacturer." },
            { step: "3", title: "Find Rajluck Game", desc: "Scroll through the list or use the search icon at the top to find the Rajluck Game app entry." },
            { step: "4", title: "Tap Permissions", desc: "Inside the app info page, tap the Permissions option to see a full list of all permissions the app holds." },
            { step: "5", title: "Toggle Permissions On or Off", desc: "Tap any permission to change it to 'Allow', 'Deny', or 'Ask every time'. Changes take effect immediately without restarting the app." },
          ].map((item) => (
            <li key={item.step} className="flex gap-4 items-start">
              <span className="step-number flex-shrink-0">{item.step}</span>
              <div>
                <h4 className="font-bold text-text-primary mb-1">{item.title}</h4>
                <p className="text-text-secondary text-sm">{item.desc}</p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      {/* FAQ */}
      <section className="section-padding bg-primary-50 max-w-full">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold gradient-text mb-8">Installation FAQ</h2>
          <div className="space-y-6">
            {[
              { q: "Why does Rajluck Game need storage permission?", a: "Storage permission is used to cache game assets locally, which reduces loading times on repeat visits and saves mobile data. The app only accesses files within its own designated directory and cannot read your personal photos or documents." },
              { q: "Is it safe to enable 'Install from Unknown Sources' for Rajluck?", a: "Yes, when downloading from the official source at rajluckgamers.com. We recommend disabling 'Install from Unknown Sources' again after installation to maintain general device security. Only re-enable it for trusted official APK sources." },
              { q: "What happens if I deny the notification permission?", a: "The app will still function normally. You will simply not receive push alerts for bonuses, login confirmations, or session reminders. You can re-enable notifications at any time from Android Settings." },
              { q: "Does Rajluck Game access my contacts or location?", a: "No. Rajluck Game does not request access to your contacts, location, camera, or microphone. It only requires the permissions listed above — all of which are directly tied to app functionality." },
              { q: "Can I use Rajluck Game without granting any permissions?", a: "Internet access is non-negotiable — without it the app cannot connect to servers. All other permissions can be denied; however, some features like push notifications and caching will be unavailable." },
            ].map((faq) => (
              <div key={faq.q} className="card p-6">
                <h3 className="font-bold text-text-primary mb-2">{faq.q}</h3>
                <p className="text-text-secondary text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="hero-gradient-soft section-padding text-center">
        <h2 className="text-3xl font-bold text-black mb-4">Install Rajluck Game in Minutes</h2>
        <p className="text-black/70 mb-8 max-w-xl mx-auto">Download the official APK, grant the permissions you are comfortable with, and start playing today.</p>
        <a href={CTA_LINK} target="_blank" rel="noopener noreferrer" className="btn-cta inline-block text-lg font-bold px-10 py-4 rounded-full shadow-xl">
          Get Rajluck APK
        </a>
      </section>

      {/* Internal Links */}
      <section className="section-padding max-w-4xl mx-auto">
        <h2 className="text-xl font-bold text-text-primary mb-4">More Installation Help</h2>
        <div className="flex flex-wrap gap-3">
          <Link href="/rajluck-download" className="btn-outline px-4 py-2 rounded-full text-sm">Download Guide</Link>
          <Link href="/rajluck-game-apk-download" className="btn-outline px-4 py-2 rounded-full text-sm">APK File Verification</Link>
          <Link href="/rajluck-game-update" className="btn-outline px-4 py-2 rounded-full text-sm">Update Guide</Link>
          <Link href="/rajluck-game-latest-version" className="btn-outline px-4 py-2 rounded-full text-sm">Latest Version</Link>
          <Link href="/rajluck-game-free" className="btn-outline px-4 py-2 rounded-full text-sm">Is It Free?</Link>
          <Link href="/rajluck-game-play" className="btn-outline px-4 py-2 rounded-full text-sm">How to Play</Link>
        </div>
      </section>
    </main>
  );
}
